import Foundation

func L(_ key: String) -> String {
    let lang = UserDefaults.standard.string(forKey: "walletai_language") ?? "en"
    return _lStrings[lang]?[key] ?? _lStrings["en"]?[key] ?? key
}

private let _lStrings: [String: [String: String]] = ["en": _lEN, "es": _lES]

private let _lEN: [String: String] = [
    // Tab bar
    "tab.dashboard":     "Dashboard",
    "tab.transactions":  "Transactions",
    "tab.ai":            "AI",
    "tab.categories":    "Categories",

    // Dashboard
    "dashboard.title":         "WalletAI",
    "dashboard.netBalance":    "Net Balance",
    "dashboard.income":        "Income",
    "dashboard.expenses":      "Expenses",
    "dashboard.week":          "Week",
    "dashboard.month":         "Month",
    "dashboard.year":          "Year",
    "dashboard.monthlyBudget": "Monthly Budget",
    "dashboard.used":          "used",
    "dashboard.totalSpent":    "Total Spent",
    "dashboard.last7Days":     "Last 7 Days",
    "dashboard.byCategory":    "By Category",
    "dashboard.recent":        "Recent",
    "dashboard.seeAll":        "See All",
    "dashboard.comingSoon":    "Coming Soon",
    "dashboard.expected":      "Expected",

    // Transactions
    "tx.title":          "Transactions",
    "tx.searchPrompt":   "Search transactions",
    "tx.all":            "All",
    "tx.expenses":       "Expenses",
    "tx.income":         "Income",
    "tx.empty":          "No transactions yet",
    "tx.emptyHint":      "Tap + or use voice to add your first transaction",
    "tx.today":          "Today",
    "tx.yesterday":      "Yesterday",
    "tx.edit":           "Edit",
    "tx.delete":         "Delete",
    "tx.addExpense":     "Add Expense",
    "tx.addIncome":      "Add Income",
    "tx.saveExpense":    "Save Expense",
    "tx.saveIncome":     "Save Income",
    "tx.editTx":         "Edit Transaction",
    "tx.title_field":    "Title",
    "tx.notes":          "Notes (optional)",
    "tx.date":           "Date",
    "tx.recurring":      "Recurring",
    "tx.interval":       "Interval",
    "tx.category":       "Select Category",
    "tx.voiceHint":      "Speak a transaction, e.g. \u{201C}Spent $5 on coffee\u{201D}",

    // Categories
    "cat.title":         "Categories",
    "cat.totalBudget":   "Total Budget",
    "cat.monthSpent":    "Month Spent",
    "cat.budgetOverview":"Budget Overview",
    "cat.all":           "All Categories",
    "cat.hint":          "Hold any card to edit or delete",
    "cat.newCategory":   "New Category",
    "cat.editCategory":  "Edit Category",
    "cat.icon":          "Icon",
    "cat.quickPicks":    "Quick picks",
    "cat.color":         "Color",
    "cat.monthlyBudget": "Monthly Budget",
    "cat.budgetAmount":  "Budget Amount",
    "cat.typeEmoji":     "Type any emoji",
    "cat.createCategory":"Create Category",
    "cat.updateCategory":"Update Category",
    "cat.chooseCategory":"Choose Category",

    // AI Chat
    "ai.title":          "AI Assistant",
    "ai.welcome":        "Meet your AI Finance Assistant",
    "ai.welcomeHint":    "Ask anything about your spending, get insights, or let me help you track expenses via voice.",
    "ai.quickQuestions": "Quick Questions",
    "ai.inputPlaceholder":"Ask about your finances...",
    "ai.q1":             "How much have I spent this month?",
    "ai.q2":             "What's my biggest spending category?",
    "ai.q3":             "Am I over budget?",
    "ai.q4":             "Give me 3 tips to save more money",
    "ai.menuSummary":    "Financial Summary",
    "ai.menuTips":       "Saving Tips",
    "ai.menuBiggest":    "Biggest Expenses",
    "ai.menuSetKey":     "Set API Key",
    "ai.menuClear":      "Clear Chat",
    "ai.setupKey":       "Set Up Groq API Key",
    "ai.noKey":          "Please add your Groq API key — tap the ⋯ menu above.",

    // Settings
    "settings.title":    "Settings",
    "settings.profile":  "Profile",
    "settings.budget":   "Budget",
    "settings.ai":       "AI",
    "settings.automation":"Automation",
    "settings.appearance":"Appearance",
    "settings.preferences":"Preferences",
    "settings.data":     "Data",
    "settings.about":    "About",
    "settings.language": "Language",
    "settings.colorTheme":"Color Theme",
    "settings.personality":"Personality",
    "settings.budgetAlerts":"Budget Alerts",
    "settings.faceID":   "Face ID Lock",
    "settings.exportCSV":"Export CSV",
    "settings.export":   "Export",
    "settings.deleteAll":"Delete All Data",
    "settings.delete":   "Delete",
    "settings.reAnalyze":"Re-analyze Transactions",
    "settings.reAnalyzeHint":"AI will sort every transaction into the right category",
    "settings.analyze":  "Analyze",
    "settings.applePay": "Apple Pay Auto-Log",
    "settings.voice":    "Voice Recognition",
    "settings.alwaysOn": "Always On",
    "settings.setup":    "Setup →",
    "settings.theme":    "Theme",
    "settings.yourName": "Your name",
    "settings.yourEmail":"Email (optional)",
    "settings.saveProfile":"Save Profile",
    "settings.profileSaved":"Profile saved!",
    "settings.monthlyLimit":"Monthly Budget Limit",
    "settings.currency": "Currency",
    "settings.save":     "Save",

    // Common
    "common.cancel":     "Cancel",
    "common.save":       "Save",
    "common.done":       "Done",
    "common.edit":       "Edit",
    "common.delete":     "Delete",
    "common.of":         "of",
    "common.budget":     "budget",
    "common.english":    "🇺🇸 English",
    "common.spanish":    "🇸🇻 Español",
    "common.personality.chill":  "Chill",
    "common.personality.girly":  "Girlie 🎀",
    "common.copy":       "Copy",
    "common.transactions": "Transactions",

    // Settings extras
    "settings.monthlyLimitRow":  "Monthly Limit",
    "settings.setLimit":         "Set limit",
    "settings.aiSection":        "AI Assistant",
    "settings.groqKey":          "Groq API Key",
    "settings.configured":       "Configured ✓",
    "settings.addKey":           "Add Key",
    "settings.modelRow":         "Model",
    "settings.colorSchemeRow":   "Color Scheme",
    "settings.systemScheme":     "System",
    "settings.lightScheme":      "Light",
    "settings.darkScheme":       "Dark",
    "settings.deleteEverything": "Delete Everything",
    "settings.walletaiUser":     "WalletAI User",
    "settings.setupProfileHint": "Set up your profile",
    "settings.txTracked":        "transactions tracked",
    "settings.setBudget":        "Set Budget",
]

private let _lES: [String: String] = [
    // Tab bar
    "tab.dashboard":     "Panel",
    "tab.transactions":  "Transacciones",
    "tab.ai":            "IA",
    "tab.categories":    "Categorías",

    // Dashboard
    "dashboard.title":         "WalletAI",
    "dashboard.netBalance":    "Saldo Neto",
    "dashboard.income":        "Ingresos",
    "dashboard.expenses":      "Gastos",
    "dashboard.week":          "Semana",
    "dashboard.month":         "Mes",
    "dashboard.year":          "Año",
    "dashboard.monthlyBudget": "Presupuesto Mensual",
    "dashboard.used":          "usado",
    "dashboard.totalSpent":    "Total Gastado",
    "dashboard.last7Days":     "Últimos 7 Días",
    "dashboard.byCategory":    "Por Categoría",
    "dashboard.recent":        "Reciente",
    "dashboard.seeAll":        "Ver Todo",
    "dashboard.comingSoon":    "Próximamente",
    "dashboard.expected":      "Esperado",

    // Transactions
    "tx.title":          "Transacciones",
    "tx.searchPrompt":   "Buscar transacciones",
    "tx.all":            "Todos",
    "tx.expenses":       "Gastos",
    "tx.income":         "Ingresos",
    "tx.empty":          "Sin transacciones aún",
    "tx.emptyHint":      "Toca + o usa voz para agregar tu primera transacción",
    "tx.today":          "Hoy",
    "tx.yesterday":      "Ayer",
    "tx.edit":           "Editar",
    "tx.delete":         "Eliminar",
    "tx.addExpense":     "Agregar Gasto",
    "tx.addIncome":      "Agregar Ingreso",
    "tx.saveExpense":    "Guardar Gasto",
    "tx.saveIncome":     "Guardar Ingreso",
    "tx.editTx":         "Editar Transacción",
    "tx.title_field":    "Título",
    "tx.notes":          "Notas (opcional)",
    "tx.date":           "Fecha",
    "tx.recurring":      "Recurrente",
    "tx.interval":       "Intervalo",
    "tx.category":       "Seleccionar Categoría",
    "tx.voiceHint":      "Di una transacción, ej. \u{201C}Gasté $5 en café\u{201D}",

    // Categories
    "cat.title":         "Categorías",
    "cat.totalBudget":   "Presupuesto Total",
    "cat.monthSpent":    "Gastado en el Mes",
    "cat.budgetOverview":"Resumen de Presupuesto",
    "cat.all":           "Todas las Categorías",
    "cat.hint":          "Mantén presionada para editar o eliminar",
    "cat.newCategory":   "Nueva Categoría",
    "cat.editCategory":  "Editar Categoría",
    "cat.icon":          "Ícono",
    "cat.quickPicks":    "Accesos rápidos",
    "cat.color":         "Color",
    "cat.monthlyBudget": "Presupuesto Mensual",
    "cat.budgetAmount":  "Monto del Presupuesto",
    "cat.typeEmoji":     "Escribe cualquier emoji",
    "cat.createCategory":"Crear Categoría",
    "cat.updateCategory":"Actualizar Categoría",
    "cat.chooseCategory":"Elegir Categoría",

    // AI Chat
    "ai.title":          "Asistente IA",
    "ai.welcome":        "Conoce tu Asistente de Finanzas",
    "ai.welcomeHint":    "Pregúntale cualquier cosa sobre tus gastos, obtén análisis o registra gastos por voz.",
    "ai.quickQuestions": "Preguntas Rápidas",
    "ai.inputPlaceholder":"Pregunta sobre tus finanzas...",
    "ai.q1":             "¿Cuánto he gastado este mes?",
    "ai.q2":             "¿En qué categoría gasto más?",
    "ai.q3":             "¿Estoy sobre mi presupuesto?",
    "ai.q4":             "Dame 3 consejos para ahorrar más",
    "ai.menuSummary":    "Resumen Financiero",
    "ai.menuTips":       "Consejos de Ahorro",
    "ai.menuBiggest":    "Mayores Gastos",
    "ai.menuSetKey":     "Configurar API Key",
    "ai.menuClear":      "Limpiar Chat",
    "ai.setupKey":       "Configurar Groq API Key",
    "ai.noKey":          "Agrega tu Groq API key — toca el menú ⋯ arriba.",

    // Settings
    "settings.title":    "Ajustes",
    "settings.profile":  "Perfil",
    "settings.budget":   "Presupuesto",
    "settings.ai":       "IA",
    "settings.automation":"Automatización",
    "settings.appearance":"Apariencia",
    "settings.preferences":"Preferencias",
    "settings.data":     "Datos",
    "settings.about":    "Acerca de",
    "settings.language": "Idioma",
    "settings.colorTheme":"Tema de Color",
    "settings.personality":"Personalidad",
    "settings.budgetAlerts":"Alertas de Presupuesto",
    "settings.faceID":   "Bloqueo Face ID",
    "settings.exportCSV":"Exportar CSV",
    "settings.export":   "Exportar",
    "settings.deleteAll":"Eliminar Todos los Datos",
    "settings.delete":   "Eliminar",
    "settings.reAnalyze":"Re-analizar Transacciones",
    "settings.reAnalyzeHint":"La IA organizará tus transacciones en la categoría correcta",
    "settings.analyze":  "Analizar",
    "settings.applePay": "Auto-registro Apple Pay",
    "settings.voice":    "Reconocimiento de Voz",
    "settings.alwaysOn": "Siempre Activo",
    "settings.setup":    "Configurar →",
    "settings.theme":    "Tema",
    "settings.yourName": "Tu nombre",
    "settings.yourEmail":"Correo (opcional)",
    "settings.saveProfile":"Guardar Perfil",
    "settings.profileSaved":"¡Perfil guardado!",
    "settings.monthlyLimit":"Límite Mensual",
    "settings.currency": "Moneda",
    "settings.save":     "Guardar",

    // Common
    "common.cancel":     "Cancelar",
    "common.save":       "Guardar",
    "common.done":       "Listo",
    "common.edit":       "Editar",
    "common.delete":     "Eliminar",
    "common.of":         "de",
    "common.budget":     "presupuesto",
    "common.english":    "🇺🇸 English",
    "common.spanish":    "🇸🇻 Español",
    "common.personality.chill":  "Tranquilo",
    "common.personality.girly":  "Girlie 🎀",
    "common.copy":       "Copiar",
    "common.transactions": "Transacciones",

    // Settings extras
    "settings.monthlyLimitRow":  "Límite Mensual",
    "settings.setLimit":         "Establecer límite",
    "settings.aiSection":        "Asistente IA",
    "settings.groqKey":          "Groq API Key",
    "settings.configured":       "Configurado ✓",
    "settings.addKey":           "Agregar Clave",
    "settings.modelRow":         "Modelo",
    "settings.colorSchemeRow":   "Esquema de Color",
    "settings.systemScheme":     "Sistema",
    "settings.lightScheme":      "Claro",
    "settings.darkScheme":       "Oscuro",
    "settings.deleteEverything": "Eliminar Todo",
    "settings.walletaiUser":     "Usuario WalletAI",
    "settings.setupProfileHint": "Configura tu perfil",
    "settings.txTracked":        "transacciones registradas",
    "settings.setBudget":        "Establecer Presupuesto",
]
